import Navbar from '@/components/Navbar'
import React from 'react'

export const metadata ={
  title: "Create Next App",
  description: "generated by create next app"
}

const layout = ({children}:{children: React.ReactNode}) => {
  return (
    <main className='font-work-sans'>
        <Navbar/>
        {children}
    </main>
  )
}

export default layout
