import React from 'react'
import { auth } from '@/auth'
import { SessionProvider } from "@/context/UserContaxt";


export const metadata ={
  title: "Create Next App",
  description: "generated by create next app"
}

const layout = async ({children}:{children: React.ReactNode}) => {
  const session = await auth();
  const bool = session?true:false;
  return (
      <SessionProvider initialSession={bool}>
          <main className='font-work-sans'>
              
              {children}
          </main>

      </SessionProvider>
  )
}

export default layout
