import Navbar from '@/components/Navbar'
import React from 'react'
import { auth } from '@/auth'


export const metadata ={
  title: "Create Next App",
  description: "generated by create next app"
}

const layout = async ({children}:{children: React.ReactNode}) => {
  const session = await auth();
  const bool = session?true:false;
  return (
      
          <main className='font-work-sans'>
            <Navbar search='' session={bool}/>
              
              {children}
          </main>

      
  )
}

export default layout
